
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JOSUE FLORIAN
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    RegistraUsuario usuario = new RegistraUsuario(false); 
    RegistraUsuario Administrador = new RegistraUsuario(true);
    public Main() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogIn = new javax.swing.JButton();
        btnRU = new javax.swing.JButton();
        tfIDUser = new javax.swing.JTextField();
        lbIDUser = new javax.swing.JLabel();
        lbContraseña = new javax.swing.JLabel();
        btnRA = new javax.swing.JButton();
        jpContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLogIn.setText("Log In");
        btnLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogInMouseClicked(evt);
            }
        });
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        btnRU.setLabel("Registrar Usuario");
        btnRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRUActionPerformed(evt);
            }
        });

        lbIDUser.setText("ID User:");

        lbContraseña.setText("Contraseña:");

        btnRA.setText("Resgistrar Administrador");
        btnRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogIn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbContraseña)
                            .addComponent(lbIDUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfIDUser, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(jpContrasena))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfIDUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRU))
                    .addComponent(lbIDUser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnRA)))
                .addGap(35, 35, 35)
                .addComponent(btnLogIn)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        btnLogIn.getAccessibleContext().setAccessibleName("btnLogIn");
        btnRU.getAccessibleContext().setAccessibleName("btnRU");
        tfIDUser.getAccessibleContext().setAccessibleName("tfIDUser");
        lbIDUser.getAccessibleContext().setAccessibleName("lbIDUser");
        lbContraseña.getAccessibleContext().setAccessibleName("lbContraseña");
        btnRA.getAccessibleContext().setAccessibleName("btnRA");
        jpContrasena.getAccessibleContext().setAccessibleName("jpContrasena");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRUActionPerformed
        // TODO add your handling code here:
        usuario = new RegistraUsuario(false);
        usuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRUActionPerformed

    private void btnRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRAActionPerformed
        // TODO add your handling code here:
        Administrador = new RegistraUsuario(true);
        Administrador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRAActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        char[] contrasen = jpContrasena.getPassword();
        String contra = new String(contrasen);
        //Administrador = new RegistraUsuario(true);

        Comunidad comunidad = new Comunidad();
        
        
        if (tfIDUser.equals("") || contra.equals("")) {
            JOptionPane.showMessageDialog(null, "debe llenar ambas cansillas. la primera con su ID y la segunda con su contraseña");
        }
        else{   
            System.out.println(555);  
            if (comunidad.log_in(comunidad.QueUsuario(tfIDUser.getText()), tfIDUser.getText(), contra) == true) {
                Perfil perfil = new Perfil(comunidad.QueUsuario(tfIDUser.getText()),comunidad.getTipoUsuario(), comunidad.getIndexUser());
                perfil.setVisible(true);
                this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(null, "ID o contraseña incorrectos. Ingrese un ID o contraseña valida ya registrada");
            }
            
            
         }
        
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnLogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnLogInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnRA;
    private javax.swing.JButton btnRU;
    private javax.swing.JPasswordField jpContrasena;
    private javax.swing.JLabel lbContraseña;
    private javax.swing.JLabel lbIDUser;
    private javax.swing.JTextField tfIDUser;
    // End of variables declaration//GEN-END:variables
}
